server:
  port: 5000
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://awseb-e-x7kj5mrwej-stack-awsebrdsdatabase-flkma30d5kkd.cxqc006kavce.ap-northeast-2.rds.amazonaws.com:3306/ebdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: testpm
    password: 12345678